import type { Metadata } from "next";
import "../styles/globals.css";
import { Header } from "@/components/header/header";
import { Footer } from "@/components/footer/footer";
import { OutfitFont, MulishFont, SyneFont, PoppinsFont } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

{/* add to body ${PoppinsFont.variable} - used on different/banner */}
      <body className={`
          ${OutfitFont.variable} 
          ${MulishFont.variable} 
          ${SyneFont.variable}
          
        `}
      >

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
